/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import DAO.ClienteDAO;
import DAO.ServicioDAO;
import DAO.SuscripcionDAO;
import bd.Conexion;
import com.sun.jdi.connect.spi.Connection;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Servicio;
import modelo.Suscripcion;

/**
 *
 * @author ALBERTH
 */
public class PanelClientes extends javax.swing.JPanel {

    private DefaultTableModel tableModel;
    private ClienteDAO clienteDAO;

    /**
     * Creates new form PanelClientes
     */
    public PanelClientes() {

        initComponents();
        clienteDAO = new ClienteDAO();
        inicializarTabla();
        cargarClientes(); // Cambiar a este método básico
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(1170, 728));
        setPreferredSize(new java.awt.Dimension(1214, 728));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.addTab("Directorio", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.addTab("Nuevo Contrato", jPanel3);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.addTab("Gestion de cortes", jPanel4);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 730));
    }// </editor-fold>//GEN-END:initComponents

    private void cargarClientes() {
        tableModel.setRowCount(0);
        List<Cliente> clientes = clienteDAO.obtenerTodosClientes();

        for (Cliente cliente : clientes) {
            Object[] row = {
                cliente.getIdCliente(),
                cliente.getDniCliente(),
                cliente.getNombres(),
                cliente.getApellidos(),
                cliente.getDireccion(),
                "Sin servicio",
                "Inactivo", // Temporal hasta que implementes suscripciones
                String.format("S/. %.2f", cliente.getDeuda()), // Formatear como moneda
                cliente.getCorreo(),
                cliente.getFechaRegistro()
            };
            tableModel.addRow(row);
        }
    }

    private void inicializarTabla() {
        String[] columnNames = {
            "ID", "DNI", "Nombres", "Apellidos", "Dirección", "Servicio", "Estado", "Deuda", "Email", "Fecha Registro"
        };

        tableModel = new javax.swing.table.DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };


    }

    private void cargarClientesConSuscripciones() {
        tableModel.setRowCount(0);
        List<Cliente> clientes = clienteDAO.obtenerTodosClientes();

        for (Cliente cliente : clientes) {
            // Aquí puedes agregar la lógica para obtener información de suscripción
            // Por ahora, ponemos datos de ejemplo
            String nombreServicio = "Fibra Estándar";
            String estadoSuscripcion = "Activo";

            Object[] row = {
                cliente.getIdCliente(),
                cliente.getDniCliente(),
                cliente.getNombres(),
                cliente.getApellidos(),
                cliente.getDireccion(),
                nombreServicio,
                estadoSuscripcion,
                cliente.getCorreo(),
                cliente.getFechaRegistro()
            };
            tableModel.addRow(row);
        }
    }

    private void actualizarTablaConClientes(List<Cliente> clientes) {
        tableModel.setRowCount(0);
        for (Cliente cliente : clientes) {
            Object[] row = {
                cliente.getIdCliente(),
                cliente.getDniCliente(),
                cliente.getNombres(),
                cliente.getApellidos(),
                cliente.getDireccion(),
                "Sin servicio", // Placeholder
                "Inactivo", // Placeholder
                cliente.getCorreo(),
                cliente.getFechaRegistro()
            };
            tableModel.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
