/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;
import vista.PanelClientes;

/**
 *
 * @author ALBERTH
 */
public class Principal extends javax.swing.JFrame {

    private modelo.Empleado empleadoActual;

    // CONSTRUCTOR 1: El que usa NetBeans o pruebas rápidas (Vacío)
    public Principal() {
        // Llama al constructor principal pasando 'null' como empleado
        this(null);
    }

// CONSTRUCTOR 2: El principal
    public Principal(modelo.Empleado empleado) {
        // 1. Configuración del Look and Feel (FlatLaf)
        try {
            com.formdev.flatlaf.FlatLightLaf.setup();
        } catch (Exception ex) {
            System.err.println("Error iniciando FlatLaf");
        }

        // 2. Iniciar componentes visuales
        initComponents();

        // 3. Guardar el empleado
        this.empleadoActual = empleado;

        // --- CAMBIOS AQUÍ ---
        // A. BORRA o COMENTA esta línea que forzaba pantalla completa:
        // this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); 
        // B. AGREGA esta línea para que la ventana aparezca al CENTRO de la pantalla:
        this.setLocationRelativeTo(null);
        // --------------------

        // 4. Lógica de permisos
        if (empleado != null) {
            // Usamos String.valueOf para evitar el error de tipos si usas el ID
            if (empleado.getRolIdRol() != null) {
                // Asegúrate que configurarPermisos reciba String si así lo definiste
                // configurarPermisos(String.valueOf(empleado.getRolIdRol()));
            }
            setTitle("ISP Manager - Usuario: " + empleado.getNombres());
        }
        btn_principal.doClick();

        // 5. Cargar el diseño del Sidebar
        configurarDiseñoModerno();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn_clientes = new javax.swing.JButton();
        btn_principal = new javax.swing.JButton();
        btn_servicios = new javax.swing.JButton();
        btn_pagos = new javax.swing.JButton();
        btn_instalaciones = new javax.swing.JButton();
        btn_equipos = new javax.swing.JButton();
        btn_usuarios = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        lbl_ultimoAcceso = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        btn_clientes.setText("Clientes");
        btn_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clientesActionPerformed(evt);
            }
        });

        btn_principal.setText("Dshboard");
        btn_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_principalActionPerformed(evt);
            }
        });

        btn_servicios.setText("Servicios");
        btn_servicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_serviciosActionPerformed(evt);
            }
        });

        btn_pagos.setText("Pagos");
        btn_pagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pagosActionPerformed(evt);
            }
        });

        btn_instalaciones.setText("Instalaciones");
        btn_instalaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_instalacionesActionPerformed(evt);
            }
        });

        btn_equipos.setText("Equipos");
        btn_equipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_equiposActionPerformed(evt);
            }
        });

        btn_usuarios.setText("Usuarios");
        btn_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuariosActionPerformed(evt);
            }
        });

        btn_salir.setText("Salir");

        jLabel1.setText("logo.png");

        lbl_usuario.setForeground(new java.awt.Color(204, 204, 204));
        lbl_usuario.setText("Usuario: Usuario1");

        lbl_ultimoAcceso.setForeground(new java.awt.Color(204, 204, 204));
        lbl_ultimoAcceso.setText("Ultimo acceso: 10:51");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_ultimoAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_pagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_servicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_instalaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                .addComponent(btn_equipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btn_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_pagos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_servicios, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_instalaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_equipos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                .addComponent(lbl_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_ultimoAcceso)
                .addGap(12, 12, 12))
        );

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 1214, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientesActionPerformed
        marcarBotonActivo(btn_clientes);
        // Carga el panel con pestañas de clientes
        MostrarPanel(new vista.PanelClientes());
    }//GEN-LAST:event_btn_clientesActionPerformed

    private void btn_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_principalActionPerformed
        marcarBotonActivo(btn_principal);

        // AQUÍ ESTÁ EL CAMBIO: Llamamos a panel_Gerente
        MostrarPanel(new vista.panel_Gerente());
    }//GEN-LAST:event_btn_principalActionPerformed

    private void btn_pagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pagosActionPerformed
        marcarBotonActivo(btn_pagos);
        MostrarPanel(new vista.PanelPagos());
    }//GEN-LAST:event_btn_pagosActionPerformed

    private void btn_serviciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_serviciosActionPerformed
        marcarBotonActivo(btn_servicios);
        MostrarPanel(new vista.PanelServicios());
    }//GEN-LAST:event_btn_serviciosActionPerformed

    private void btn_instalacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_instalacionesActionPerformed
        marcarBotonActivo(btn_instalaciones);
        MostrarPanel(new vista.PanelInstalaciones());
    }//GEN-LAST:event_btn_instalacionesActionPerformed

    private void btn_equiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_equiposActionPerformed
        marcarBotonActivo(btn_equipos);
        MostrarPanel(new vista.PanelEquipos());
    }//GEN-LAST:event_btn_equiposActionPerformed

    private void btn_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuariosActionPerformed
        marcarBotonActivo(btn_usuarios);
        MostrarPanel(new vista.PanelUsuarios());
    }//GEN-LAST:event_btn_usuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            // Poner esto ANTES de iniciar la ventana
            com.formdev.flatlaf.FlatLightLaf.setup();
        } catch (Exception ex) {
            System.err.println("Fallo al iniciar FlatLaf");
        }

        java.awt.EventQueue.invokeLater(() -> {
            new Principal(null).setVisible(true); // O tu constructor correspondiente
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clientes;
    private javax.swing.JButton btn_equipos;
    private javax.swing.JButton btn_instalaciones;
    private javax.swing.JButton btn_pagos;
    private javax.swing.JButton btn_principal;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_servicios;
    private javax.swing.JButton btn_usuarios;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_ultimoAcceso;
    private javax.swing.JLabel lbl_usuario;
    // End of variables declaration//GEN-END:variables
private void configurarDiseñoModerno() {
        // 1. Colores (Iguales que antes)
        java.awt.Color colorSidebar = new java.awt.Color(15, 23, 42);
        java.awt.Color colorBgRight = new java.awt.Color(241, 245, 249);

        jPanel1.setBackground(colorSidebar);
        jPanel2.setBackground(colorBgRight);

        // 2. Configurar botones CON TUS IMÁGENES
        // Asegúrate de que los nombres aquí coincidan con los archivos que pegaste en "img"
        configurarBoton(btn_principal, "Dashboard", "/img/dashboard.png");
        configurarBoton(btn_clientes, "Clientes", "/img/clientes.png");
        configurarBoton(btn_pagos, "Pagos", "/img/pagos.png");
        configurarBoton(btn_servicios, "Servicios", "/img/servicios.png");
        configurarBoton(btn_instalaciones, "Instalaciones", "/img/instalaciones.png");
        configurarBoton(btn_equipos, "Equipos", "/img/equipos.png");
        configurarBoton(btn_usuarios, "Usuarios", "/img/usuarios.png");
        configurarBoton(btn_salir, "Salir", "/img/salir.png");

        // 3. Activar el primero
        marcarBotonActivo(btn_principal);
    }

    private void configurarBoton(javax.swing.JButton btn, String texto, String rutaIcono) {
        // 1. Cargar el Icono desde la carpeta
        try {
            // getClass().getResource busca dentro de los paquetes del proyecto
            javax.swing.ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource(rutaIcono));
            btn.setIcon(icono);
        } catch (Exception e) {
            System.err.println("Error cargando icono: " + rutaIcono);
        }

        // 2. Texto y Espaciado
        btn.setText("   " + texto); // Espacio entre icono y texto
        btn.setIconTextGap(5);      // Separación extra

        // 3. Estilo Visual (Igual que antes)
        btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        btn.setForeground(new java.awt.Color(148, 163, 184)); // Gris inactivo

        // Limpieza de bordes
        btn.setBorderPainted(false);
        btn.setFocusPainted(false);
        btn.setContentAreaFilled(true);
        btn.setOpaque(true);
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn.setBackground(new java.awt.Color(15, 23, 42)); // Fondo oscuro

        btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn.setMargin(new java.awt.Insets(10, 20, 10, 10));

        // 4. Efecto Hover
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                if (btn.getBackground().getBlue() == 42) {
                    btn.setBackground(new java.awt.Color(30, 41, 59));
                }
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                if (btn.getBackground().getBlue() == 59) {
                    btn.setBackground(new java.awt.Color(15, 23, 42));
                }
            }
        });
    }

    /**
     * Transforma un botón normal en uno estilo Dashboard moderno.
     */
    private void estilarBotonMenu(javax.swing.JButton btn) {
        btn.setForeground(new Color(148, 163, 184)); // Texto gris claro (inactivo)
        btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));

        // Quitar bordes y fondos por defecto de Java
        btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 20, 12, 10)); // Espaciado interno
        btn.setFocusPainted(false);
        btn.setContentAreaFilled(false); // Transparente por defecto
        btn.setOpaque(true);
        btn.setBackground(new Color(15, 23, 42)); // Fondo igual al menú (invisible)
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        // Alineación a la izquierda para que parezca menú
        btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        // Efecto Hover (pasar el mouse)
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                // Solo cambia de color si NO está activo actualmente
                if (btn.getForeground().equals(new Color(148, 163, 184))) {
                    btn.setBackground(new Color(30, 41, 59)); // Un poco más claro al pasar mouse
                }
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                // Si no es el activo, vuelve a transparente
                if (btn.getForeground().equals(new Color(148, 163, 184))) {
                    btn.setBackground(new Color(15, 23, 42));
                }
            }
        });
    }

    /**
     * Método MÁGICO: Pinta el botón clickeado de azul brillante y apaga los
     * demás.
     */
    private void marcarBotonActivo(javax.swing.JButton btnActivo) {
        // Lista de todos tus botones
        javax.swing.JButton[] todos = {
            btn_principal, btn_clientes, btn_pagos, btn_servicios,
            btn_instalaciones, btn_equipos, btn_usuarios, btn_salir
        };

        java.awt.Color colorActivo = new java.awt.Color(37, 99, 235); // AZUL BRILLANTE (Blue 600)
        java.awt.Color colorInactivo = new java.awt.Color(15, 23, 42); // AZUL OSCURO

        for (javax.swing.JButton b : todos) {
            if (b == btnActivo) {
                b.setBackground(colorActivo);      // Fondo Azul Brillante
                b.setForeground(java.awt.Color.WHITE); // Texto Blanco
            } else {
                b.setBackground(colorInactivo);    // Fondo Oscuro
                b.setForeground(new java.awt.Color(148, 163, 184)); // Texto Gris
            }
        }
    }

    /**
     * Método para cambiar paneles
     */
    private void MostrarPanel(javax.swing.JPanel p) {
// Configuración básica del panel hijo
        p.setSize(1080, 720);
        p.setLocation(0, 0);

        // Limpiar contenido anterior
        content.removeAll();

        // --- SOLUCIÓN DEL ERROR ---
        // Forzamos el Layout a BorderLayout para que acepte el comando .CENTER
        content.setLayout(new java.awt.BorderLayout());
        // --------------------------

        content.add(p, java.awt.BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

}
